# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eff99a59f61e326b4779d8788cc87f5046c6a304bbfc2d21c39a599b50c436336c5f25625045da8dd5b9fd485d98808e486de5af8e06bba7864d86a98db87032

test:
  secret_key_base: eb8131bcc30dc6f70fcdae444a038a0a463adef1f14bfd63c276de7bc53eb752525438dbf96b00e4c6c0f9eaee813d66dc354ec22336519ce0aa82e8c398f0e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
